DBNAME = "grow.db"
DEFAULT_HUMIDITY: float = 92.0
DEFAULT_HUMIDITY_LOW: float = 2.0
DEFAULT_HUMIDITY_HIGH: float = 2.0
DEFAULT_AIR_PRD: int = 4
DEFAULT_AIR_DURATION: int = 5
FAN_PIN = 27
HUMIDIFIER_PIN = 22